# fix line endings on Windows and checkout all strings with \r\n
init:
  - git config --global core.autocrlf true

# Test against this version of Node.js
environment:
  matrix:
    # node.js
    - nodejs_version: "6.0"
    - nodejs_version: "5.0"
    - nodejs_version: "4.0"
    - nodejs_version: "0.12"
    - nodejs_version: "0.10"

platform:
  - x86
  - x64

matrix:
  fast_finish: true

cache:
  # local npm modules
  - node_modules

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install


# Post-install test scripts.
test_scripts:
  # Output useful info for debugging
  - node --version
  - npm --version
  # run tests
  - echo Run npm test
  - npm test

# Don't actually build.
build: off
